# Generated by Django 3.2 on 2022-06-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Master'), (1, 'Senior Officer'), (2, 'Junior Officer'), (3, 'Bosun')], default=3),
        ),
    ]
