# Generated by Django 3.2 on 2022-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220607_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.IntegerField(choices=[(0, 'Approved'), (1, 'Waiting For Approval'), (2, 'Approval Not Required')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], default=2),
        ),
    ]
