# Generated by Django 3.2 on 2022-06-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
