# Generated by Django 3.2 on 2022-06-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
