# Generated by Django 3.2 on 2022-06-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approval_status',
            field=models.IntegerField(choices=[(0, 'Approved'), (1, 'Waiting For Approval'), (2, 'N/R')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Completed'), (2, 'Overdue')], default=0),
        ),
    ]
